Repository lambdaclass/cairo_native, pull requests merged in 2024-05, with the labels that each got.

#544 Refactor mem libfuncs to use the BlockExt trait
  src/libfuncs/mem.rs
Labels: odhack

#536 test: from execution result
  src/execution_result.rs
  tests/tests/mod.rs
  tests/tests/result.rs
Labels: priority

#572 Increase coverage of the JIT values
  src/values.rs
Labels: priority

#537 Chore: refactor cast
  src/block_ext.rs
  src/libfuncs/cast.rs
Labels: odhack

#570 Small refactor and util for `OptLevel`
  src/bin/cairo-native-compile.rs
  src/bin/cairo-native-run.rs
  src/bin/cairo-native-test.rs
  src/executor.rs
  src/ffi.rs
  src/utils.rs
Labels: priority

#571 Refactor gas
  src/libfuncs/gas.rs
Labels: odhack

#555 Update bytes31 use blockext
  src/libfuncs/bytes31.rs
Labels: odhack

#563 Refactor bool to use BlockExt
  src/libfuncs/bool.rs
Labels: odhack

#568 Refactor ec ops
  src/libfuncs/ec.rs
Labels: odhack

#576 fix: builtin gas
  src/compiler.rs
  src/metadata/gas.rs
  tests/alexandria/src/lib.cairo
  tests/tests/alexandria.rs
Labels: bug, priority

#538 Refactor pedersen libfuncs to use the BlockExt trait
  src/libfuncs/pedersen.rs
Labels: odhack

#550 add self referencing test
  tests/tests/programs.rs
Labels: priority

#574 some refactoring
  README.md
  benches/benches.rs
  examples/erc20.rs
  examples/starknet.rs
  src/libfuncs/ec.rs
  src/libfuncs/starknet.rs
  src/libfuncs/uint128.rs
  src/utils.rs
  tests/common.rs
  tests/tests/starknet/keccak.rs
Labels: priority

#579 add unit tests for `to_jit`
  src/values.rs
Labels: review-ready

#577 add unit test for `DebugInfo::extract`
  Cargo.lock
  Cargo.toml
  src/debug_info.rs
Labels: priority, review-ready

#585 use github macos m1 runner
  .github/workflows/ci.yml
Labels: review-ready

#584 test: unit aot
  Cargo.lock
  Cargo.toml
  src/cache/aot.rs
  src/executor/aot.rs
  src/utils.rs
Labels: review-ready

#603 Fix wrong upcast from unsigned to signed
  Cargo.lock
  src/libfuncs/cast.rs
Labels: review-ready

#587 test: debug info module
  Cargo.lock
  Cargo.toml
  src/debug_info.rs
Labels: review-ready

#594 Add more docs about cairo native within the code
  src/execution_result.rs
  src/executor.rs
  src/ffi.rs
  src/lib.rs
Labels: review-ready

#597 increase test coverage of `cairo-native-test`
  src/bin/cairo-native-test.rs
Labels: review-ready

#583 increase `utils` test coverage
  src/libfuncs/struct.rs
  src/utils.rs
Labels: review-ready

#609 Fix Ignored Flag Bug
  src/bin/cairo-native-test.rs
Labels: review-ready

#611 add `SquashedFelt252Dict` in executor
  src/executor.rs
  tests/cases/cairo_vm/felt_dict_squash.cairo
  tests/common.rs
  tests/tests/cases.rs
Labels: review-ready

#566 Update to LLVM 18 (and Rust 1.78)
  .github/workflows/bench-hyperfine.yml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/rustdoc.yml
  Cargo.lock
  Cargo.toml
  Dockerfile
  Makefile
  README.md
  build.rs
  env-macos.sh
  rust-toolchain.toml
  scripts/bench-hyperfine.sh
  src/block_ext.rs
  src/compiler.rs
  src/executor.rs
  src/executor/aot.rs
  src/libfuncs.rs
  src/libfuncs/array.rs
  src/libfuncs/box.rs
  src/libfuncs/const_libfunc.rs
  src/libfuncs/debug.rs
  src/libfuncs/ec.rs
  src/libfuncs/enum.rs
  src/libfuncs/felt252.rs
  src/libfuncs/felt252_dict_entry.rs
  src/libfuncs/function_call.rs
  src/libfuncs/nullable.rs
  src/libfuncs/pedersen.rs
  src/libfuncs/poseidon.rs
  src/libfuncs/starknet.rs
  src/libfuncs/starknet/secp256.rs
  src/metadata/debug_utils.rs
  src/metadata/realloc_bindings.rs
  src/metadata/runtime_bindings.rs
  src/starknet.rs
  src/types.rs
  src/types/array.rs
  src/types/box.rs
  src/types/felt252_dict.rs
  src/types/felt252_dict_entry.rs
  src/types/nullable.rs
  src/types/squashed_felt252_dict.rs
  src/types/starknet.rs
  src/utils.rs
  src/values.rs
  tests/tests/boolean.rs
  tests/tests/cases.rs
  tests/tests/programs.rs
  tests/tests/starknet/programs/syscalls.cairo
  tests/tests/starknet/syscalls.rs
Labels: priority, review-ready

#605 Fix integer casting
  cairo-tests/src/integer_test.cairo
  src/libfuncs/cast.rs
Labels: review-ready

#608 dev: remove unused mutex
  src/bin/cairo-native-test.rs
Labels: review-ready

#620 Apply missed fixes on llvm 18 pr
  README.md
  src/executor.rs
  src/libfuncs/felt252_dict_entry.rs
  src/starknet.rs
Labels: priority, review-ready

#610 Add Bytes31 return type
  src/bin/cairo-native-run.rs
  src/executor.rs
  src/libfuncs/cast.rs
  src/types.rs
  src/values.rs
  tests/common.rs
  tests/tests/cases.rs
Labels: review-ready

#619 Fix bounded int casts
  cairo-tests/src/integer_test.cairo
  src/bin/cairo-native-run.rs
  src/bin/cairo-native-test.rs
  src/libfuncs/cast.rs
  src/types.rs
  src/types/bounded_int.rs
  src/values.rs
Labels: review-ready

#627 Parse Result Error
  src/executor.rs
  src/executor/aot.rs
  src/executor/jit.rs
Labels: review-ready

#636 Add concurrency to `ci` workflow
  .github/workflows/ci.yml
Labels: process

#629 fix: function_call libfunc
  src/libfuncs/function_call.rs
  tests/common.rs
  tests/tests/programs.rs
Labels: review-ready
